# Generated by Django 4.2.3 on 2023-08-07 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='practice/thumbnail/%Y%m%d')),
                ('create_story', models.TextField()),
                ('review', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=30)),
                ('file', models.TextField()),
                ('file_type', models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Voice'), (4, 'Document')], default=1)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='posts.practice')),
            ],
        ),
    ]
