# Generated by Django 4.2.3 on 2023-08-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_rename_program_id_contents_program_and_more'),
        ('posts', '0006_tip_tip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip_Tag_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.tag')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tip')),
            ],
        ),
    ]
