# Generated by Django 4.2.3 on 2023-08-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_tip_tag_map_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip_tag_map',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag'),
        ),
    ]
