# Generated by Django 4.2.3 on 2023-08-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_tip_tag_map_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetpost',
            name='agora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.agora'),
        ),
        migrations.AddField(
            model_name='targetpost',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.tip'),
        ),
    ]
