# Generated by Django 4.2.3 on 2023-08-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_program_user_map_evaluation'),
        ('posts', '0012_remove_evaluation_program_user_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_Tag_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.practice')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.tag')),
            ],
        ),
    ]
