# Generated by Django 4.2.3 on 2023-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_agora_cons_agora_pros'),
    ]

    operations = [
        migrations.AddField(
            model_name='agora',
            name='my_opinion_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pros'), (2, 'Cons')], null=True),
        ),
    ]
