# Generated by Django 4.2.3 on 2023-08-18 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.targetpost'),
        ),
    ]
