# Generated by Django 4.2.3 on 2023-08-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_comment_target_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.targetpost'),
        ),
        migrations.AlterField(
            model_name='targetpost',
            name='agora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.agora'),
        ),
        migrations.AlterField(
            model_name='targetpost',
            name='practice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.practice'),
        ),
        migrations.AlterField(
            model_name='targetpost',
            name='qna',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.qna'),
        ),
        migrations.AlterField(
            model_name='targetpost',
            name='tip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.tip'),
        ),
    ]
