# Generated by Django 4.2.3 on 2023-08-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_comment_target_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pros_and_cons',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pros'), (2, 'Cons')], null=True),
        ),
    ]
