# Generated by Django 4.2.3 on 2023-08-18 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_liked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked',
            new_name='PostLiked',
        ),
    ]
