# Generated by Django 4.2.3 on 2023-08-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0023_rename_liked_postliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agora_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agora_comment', to='posts.comment')),
                ('tip_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tip_comment', to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgoraCommentLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agora_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
