# Generated by Django 4.2.3 on 2023-08-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_tipcommentliked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLiked',
        ),
    ]
