# Generated by Django 4.2.3 on 2023-08-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_remove_program_user_map_progress'),
        ('posts', '0026_delete_commentliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA_Tag_Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.qna')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.tag')),
            ],
        ),
    ]
