# Generated by Django 4.2.3 on 2023-08-10 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_rename_qna_id_qna_image_qna_targetpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.PositiveSmallIntegerField(choices=[(1, 'Abuse'), (2, 'Sexual content'), (3, 'Misinformation'), (4, 'Etc')], default=4)),
                ('content', models.TextField(blank=True, default='')),
                ('target_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.targetpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
