# Generated by Django 4.2.3 on 2023-08-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.FileField(upload_to='assignment/submit/%Y%m%d')),
                ('guide_text', models.TextField(default='')),
                ('guide_ref', models.FileField(upload_to='assignment/guide_ref/%Y%m%d')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('introduce', models.TextField()),
                ('review', models.TextField(default='')),
                ('thumbnail', models.ImageField(upload_to='program/%Y%m%d')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.assignment')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.BooleanField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='tag',
            field=models.ManyToManyField(related_name='Program_Tags_Map', to='programs.tags'),
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
    ]
