# Generated by Django 4.2.3 on 2023-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submit',
            field=models.FileField(blank=True, null=True, upload_to='assignment/submit/%Y%m%d'),
        ),
    ]
