# Generated by Django 4.2.3 on 2023-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_assignment_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='guide_ref',
            field=models.FileField(upload_to='programs/assignment/guide_ref/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submit',
            field=models.FileField(blank=True, null=True, upload_to='programs/assignment/submit/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='program',
            name='thumbnail',
            field=models.ImageField(upload_to='programs/thumbnail/%Y%m%d'),
        ),
    ]
