# Generated by Django 4.2.3 on 2023-08-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_assignment_guide_ref_alter_assignment_submit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
