# Generated by Django 4.2.3 on 2023-08-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_rename_tag_tags_name_remove_program_tag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_Tags_Map',
            new_name='Program_Tag_Map',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
