# Generated by Django 4.2.3 on 2023-08-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_rename_program_tags_map_program_tag_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_tag_map',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.tag'),
        ),
    ]
