# Generated by Django 4.2.3 on 2023-08-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_tag_map_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='program_id',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='program_tag_map',
            old_name='program_id',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program_tag_map',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='program_id',
            new_name='program',
        ),
    ]
