# Generated by Django 4.2.3 on 2023-08-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_program_user_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='review',
        ),
    ]
