# Generated by Django 4.2.3 on 2023-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_remove_program_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_user_map',
            name='is_want',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[(1, 'O'), (2, 'X')]),
        ),
    ]
