# Generated by Django 4.2.3 on 2023-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_program_user_map_is_want_alter_quiz_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program_user_map',
            old_name='is_want',
            new_name='participate',
        ),
        migrations.AddField(
            model_name='program_user_map',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program_user_map',
            name='wish',
            field=models.BooleanField(default=False),
        ),
    ]
