# Generated by Django 4.2.3 on 2023-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_alter_program_user_map_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_user_map',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to='programs/assignment/submit/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Communication'), (2, 'Technology'), (3, 'Information'), (4, 'Social'), (5, 'Culture')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
