# Generated by Django 4.2.3 on 2023-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_program_user_map_assignment_alter_program_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_user_map',
            name='last_content',
            field=models.IntegerField(default=0),
        ),
    ]
