# Generated by Django 4.2.3 on 2023-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_program_user_map_last_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_user_map',
            name='progress',
        ),
    ]
